title: Scott Richardson
description: Learning Cybersecurity
remote_theme: jekyll/minima

minima:
  skin: dark


url: "https://scottrichardsonsec.dev"

author: Scott Richardson

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-remote-theme